source 'https://github.com/CocoaPods/Specs.git'

target 'FMDBHelper', :exclusive => true do
  pod "FMDB", "2.5"
  pod "FMDBHelper", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FMDB", "2.5"
  pod "FMDBHelper", :path => "../"

  pod 'Kiwi'
end
